FROM node:14.0.0 as build

LABEL author="Ryan Pedersen"

WORKDIR /demo-app

COPY package*.json ./

RUN npm install

COPY . ./

RUN npm run build

FROM nginx:1.26.1-alpine3.19

COPY --from=build /demo-app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]